apiVersion: v1
kind: Secret
metadata:
    name: ai-jakegaylor-com-infisical-auth
    namespace: ai-jakegaylor-com
type: Opaque
stringData:
    clientId: ENC[AES256_GCM,data:liBrlHi7u7sRwIsYhwfzxsB7a+raS8c3Q/rnD7f0cDsIdLPJ,iv:42orHxQfZoGEjtweK9Rc19EUaU2mrjulZiNmc6SOAzo=,tag:WvdtdvcJ2VaPibk9v44lwQ==,type:str]
    clientSecret: ENC[AES256_GCM,data:T1JvVV0mUipezximtwOMW1S+7cAwffxZJ38rNJwIutWL/wAabRIPTvQRkE/yJjQqh9Lc6MvGcITXdXB9MOiYig==,iv:QdoWjMUA/4qUcBkzUGDXjqfKQwzaUCy3lI+M9FHzBLs=,tag:MPccifLxx981ZBKVI8lGnQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwT01FQ3h3NHdSVk9GOVJi
            VmhjUXJnUTZIdHZFdnpuVGNUeG85WTZxWGxZCnR0ZlVrRkNzN1FsZGlieWhYS1lX
            aVVzdU1uVk9SMUc0NklUVjQrN1B2ZWsKLS0tIHZkbVBldEpFTERCeldWbHNobHE1
            MVJwOGhkQzNrT1hvZS84T0dodW05dWcK2flzGAlonMZYgN2BOgoKWOYBVFFWGckb
            ZoqeGjLQrHeKmvmVIRf7ran59hzvH77QzZ34UfCBT25MlvrrHVGDdw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1gqdqq7uagezyew5uvhylgcasuntmltqx3mdxmwa6es5k393hg3ns4fsyrt
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-10T04:33:15Z"
    mac: ENC[AES256_GCM,data:u6FPOZk55Qn4idRsN1YebHIxnyxd/lHl3u8M8uFp5H9NGFBdpG2Lmkh7LZ1RIHWqEHSqLDaDZVFIwRllx9SSPEXSo62GL7x9KRsXpissaw6JjXca4Ybua6sqmHt9WCvYp98vLDnI8fsl7bEy2IefgvEFBhQU8b/6zosujWOPKY4=,iv:d3yId2Y9NR8oZk0BCUVQRuiDrXbhApBfjck7iK/t9AU=,tag:pxP41nG00kNo8gXVdwA3vg==,type:str]
    version: 3.13.0
